#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
#=================================================

name: 编译 mt7981系列 固件

# 以下开关，触发工作流
on: 
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 工作流完毕
      uses: actions/checkout@main

    - name: 初始化环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'        sudo -E apt-get clean
    - name: 下载源码和分支
      env: 
        REPO_URL: https://github.com/hanwckf/immortalwrt-mt798x
        REPO_BRANCH: openwrt-21.02
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        echo "src-git ssrp https://github.com/hanwckf/immortalwrt-mt798x.git" >> ./feeds.conf.default
    - name: 更新安装feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
  
    - name: 加载config
      working-directory: ./openwrt
      run: |
        cp -f defconfig/mt7981-ax3000.config .config
        make defconfig
        
    - name: 下载软件包
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    - name: 多线程编译
      working-directory: ./openwrt
      run: |
        make -j$(nproc)
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        
    - name : 打包固件
      uses: actions/upload-artifact@main
      with:
        name: immortalwrt-mt7981${{ env.FILE_DATE }}
        path: openwrt/bin/targets/
